#!/usr/bin/env python3
"""Build Tauri v2 `latest.json` for GitHub Releases auto-updates.

Scans the staged release assets (`assets/codegraph-<target>-<file>`,
as produced by the workflow's staging step), picks each platform's updater
archive plus its `.sig` signature file (both generated by `tauri build`
when `bundle.createUpdaterArtifacts` is true and `TAURI_SIGNING_PRIVATE_KEY`
is set), and writes the `latest.json` manifest Tauri's updater polls.

Platform attribution comes from the `codegraph-<target>-` filename prefix
(NOT from file names — macOS `.app.tar.gz` files carry no arch suffix),
and the `url` points at the staged (prefixed) asset name, which is what
`gh release create` actually uploads.

Usage:
    python3 scripts/generate-latest-json.py \
        --assets-dir assets \
        --tag v3.0.4 \
        --repo ajithrt007/code-graph \
        --config apps/desktop/src-tauri/tauri.conf.json \
        --notes-file /tmp/release-body.md \
        --out assets/latest.json

Fails closed: version/tag mismatch, missing signatures, or zero platforms
are all hard errors (a bad manifest is worse than none — a version
mismatch would make every install update-loop forever).
"""

import argparse
import datetime
import json
import sys
from pathlib import Path
from typing import Dict, Optional

# Staged-asset filename prefix -> Tauri updater platform key.
TARGET_PLATFORMS = {
    "codegraph-macos-x64-": "darwin-x86_64",
    "codegraph-macos-arm64-": "darwin-aarch64",
    "codegraph-windows-x64-": "windows-x86_64",
    "codegraph-windows-arm64-": "windows-aarch64",
    "codegraph-linux-x64-": "linux-x86_64",
    "codegraph-linux-arm64-": "linux-aarch64",
}

# Updater archive suffix preference per platform (first match wins).
ARCHIVE_SUFFIXES = (".nsis.zip", ".msi.zip", ".app.tar.gz", ".AppImage.tar.gz")


def split_target(name: str) -> Optional[tuple]:
    for prefix, platform in TARGET_PLATFORMS.items():
        if name.startswith(prefix):
            return platform, name[len(prefix):]
    return None


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--assets-dir", required=True)
    parser.add_argument("--tag", required=True, help="e.g. v3.0.4")
    parser.add_argument("--repo", required=True, help="e.g. ajithrt007/code-graph")
    parser.add_argument("--config", required=True, help="path to tauri.conf.json")
    parser.add_argument("--notes-file", default=None)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    tag_version = args.tag[1:] if args.tag.startswith("v") else args.tag
    with open(args.config, encoding="utf-8") as f:
        app_version = json.load(f)["version"]
    if tag_version != app_version:
        print(
            f"tag {args.tag} (version {tag_version}) != tauri.conf.json "
            f"version {app_version}; bump the app version first, or every "
            f"install will update-loop forever",
            file=sys.stderr,
        )
        return 1

    notes = ""
    if args.notes_file:
        notes = Path(args.notes_file).read_text(encoding="utf-8").strip()

    assets_dir = Path(args.assets_dir)
    # platform -> (staged asset name, original file name)
    candidates: Dict[str, tuple] = {}
    for path in sorted(assets_dir.iterdir()):
        if not path.is_file() or path.name == "latest.json":
            continue
        split = split_target(path.name)
        if split is None:
            continue
        platform, original = split
        if not any(original.endswith(suffix) for suffix in ARCHIVE_SUFFIXES):
            continue
        sig = path.parent / (path.name + ".sig")
        if not sig.is_file():
            continue
        current = candidates.get(platform)
        # Prefer earlier ARCHIVE_SUFFIXES entries (nsis over msi).
        rank = next(i for i, s in enumerate(ARCHIVE_SUFFIXES) if original.endswith(s))
        if current is None or rank < current[2]:
            candidates[platform] = (path.name, original, rank)

    platforms: Dict[str, Dict[str, str]] = {}
    for platform, (staged, _original, _rank) in sorted(candidates.items()):
        signature = (assets_dir / (staged + ".sig")).read_text(encoding="utf-8").strip()
        if not signature:
            print(f"error: empty signature for {staged}", file=sys.stderr)
            return 1
        url = f"https://github.com/{args.repo}/releases/download/{args.tag}/{staged}"
        platforms[platform] = {"signature": signature, "url": url}
        print(f"{platform}: {staged}")

    if not platforms:
        print("error: no signed updater archives found for any platform", file=sys.stderr)
        return 1

    manifest = {
        "version": tag_version,
        "notes": notes,
        "pub_date": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "platforms": platforms,
    }
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {out} ({len(platforms)} platforms)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
